---
- shell: |
    set -o pipefail
    . /home/stack/openrc.sh
    OPT_ADDITIONAL_PARAMETERS="-e @/etc/dci-ansible-agent/settings.yml" bash /home/stack/.quickstart/tripleo-quickstart/devmode.sh --release rhos-baseos-undercloud-dci --no-gate --ovb -d 2>&1|tee /home/stack/run.log
  become: True
  become_user: stack
- name: install Python shade module
  command: easy_install shade
  become: True
- os_server_facts:
    server: '*undercloud*'
    cloud: local
- set_fact: undercloud_ip='{{ openstack_servers[0]["interface_ip"] }}'
- name: Add undercloud
  add_host:
    name: "undercloud"
    groups: "undercloud"
    ansible_fqdn: "{{ undercloud_ip }}"
    ansible_user: "stack"
    ansible_host: "{{ undercloud_ip }}"
