# note: used in the context of image promotion pipeline only!
release: newton
osp_release: rhos-10

undercloud_image_url: http://192.168.1.100/rhel-guest-image-7.3-35.x86_64.qcow2
overcloud_image_url: file:///usr/share/rhosp-director-images/overcloud-full.tar
ipa_image_url: file:///usr/share/rhosp-director-images/ironic-python-agent.tar

mtu: 1350
mtu_interface: eth0

images:
    - name: rhel
      url: "{{ undercloud_image_url }}"
      type: qcow2
      md5sum: "0bfff47b55a9428c83d2235da9d470de  rhel-guest-image-7.3-35.x86_64.qcow2"
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar

inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"
repos:
  - type: file
    filename: dci_repo.repo
    down_url: http://192.168.1.100/dci_repo/dci_repo.repo
repo_cmd_after: |
  yum clean all
  if ! [[ $(hostname) == "undercloud" ]];then
    yum -y remove rhosp-director-images.noarch
    yum -y install rhosp-director-images.noarch
    md5sum /usr/share/rhosp-director-images/overcloud-full.tar > /usr/share/rhosp-director-images/overcloud-full.tar.md5
    md5sum /usr/share/rhosp-director-images/ironic-python-agent.tar > /usr/share/rhosp-director-images/ironic-python-agent.tar.md5
  fi

undercloud_ip_retries: 30
undercloud_setup: true
virthost_repo_setup: true
baseos_as_undercloud: true
use_external_images: true
download_overcloud_images: false
ovb_setup_connectivity: false
non_root_user_setup: true
package_installs: true
hostname_correction: true
selinux_enforcing: true
